function [files,recordingRange]=readRecordingRange(filename)
%% Import data from text file.
% Script for importing data from the following text file:
%
%    D:\RecordingRanges\DY1407_EK60.csv
%
% To extend the code to different selected data or a different text file,
% generate a function instead of a script.

% Auto-generated by MATLAB on 2017/08/31 15:23:44

%% Initialize variables.
delimiter = ',';
startRow = 2;

%% Format string for each line of text:
%   column1: text (%q)
%	column2: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%q%q%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, 'Delimiter', delimiter, 'EmptyValue' ,NaN,'HeaderLines' ,startRow-1, 'ReturnOnError', false);

%% Close the text file.
fclose(fileID);

%% Allocate imported array to column variable names
files = cellfun(@(x) x(1:end-4),dataArray{:,1},'UniformOutput', false);
recordingRange = cellfun(@str2double,dataArray{:,2});

%% Clear temporary variable
clearvars filename delimiter startRow formatSpec fileID dataArray ans;